#!/usr/bin/env bash
#
# update_kstars.sh — build a newer KStars, package it, and swap it into
# /Applications/kstars.app. Same workflow as install.sh's steps 4-6, split
# out for when you already have Craft bootstrapped and just want to update.
# See README.md ("Updating to a newer KStars") for the manual equivalent.
#
# Usage:
#   ./update_kstars.sh
#   CRAFT_PREFIX=/other/path ./update_kstars.sh
#
# Requires an existing Craft install at $CRAFT_PREFIX (default: ~/CraftRoot)
# — run install.sh first if you don't have one yet.

set -euo pipefail

CRAFT_PREFIX="${CRAFT_PREFIX:-$HOME/CraftRoot}"

log() { echo ""; echo "== $* =="; }

if [[ ! -f "$CRAFT_PREFIX/craft/craftenv.sh" ]]; then
	echo "error: no Craft install found at $CRAFT_PREFIX. Run install.sh first." >&2
	exit 1
fi

# shellcheck disable=SC1091
source "$CRAFT_PREFIX/craft/craftenv.sh"

# ---------------------------------------------------------------------------
# 1. Bauen: check for and pull in a newer KStars/INDI
# ---------------------------------------------------------------------------
log "Checking for a newer KStars"
craft --check-for-updates kstars || true

log "Building KStars (rebuilds INDI too if it changed)"
craft kstars

# ---------------------------------------------------------------------------
# 2. DMG: package a fresh self-contained .dmg
# ---------------------------------------------------------------------------
log "Packaging a self-contained .dmg"
craft --package kstars

DMG=$(find "$CRAFT_PREFIX/tmp" -maxdepth 1 -iname "kstars-*.dmg" -newer "$CRAFT_PREFIX/craft/craftenv.sh" 2>/dev/null | head -1)
if [[ -z "$DMG" ]]; then
	DMG=$(find "$CRAFT_PREFIX/tmp" -maxdepth 1 -iname "kstars-*.dmg" 2>/dev/null | sort | tail -1)
fi
if [[ -z "$DMG" ]]; then
	echo "error: craft --package succeeded but no .dmg found under $CRAFT_PREFIX/tmp" >&2
	exit 1
fi
echo "DMG: $DMG"

# ---------------------------------------------------------------------------
# 3. DMG updaten: swap it into /Applications/kstars.app
# ---------------------------------------------------------------------------
log "Installing the updated app to /Applications/kstars.app"
MOUNT_DIR=$(mktemp -d /tmp/kstars-dmg-mount.XXXXXX)
hdiutil attach "$DMG" -nobrowse -mountpoint "$MOUNT_DIR" >/dev/null
rm -rf /Applications/kstars.app
cp -R "$MOUNT_DIR/kstars.app" /Applications/kstars.app
xattr -cr /Applications/kstars.app
hdiutil detach "$MOUNT_DIR" >/dev/null

# Recycle KStars' private D-Bus launchd job (see README's "Known gotcha"). The
# job caches the *code requirement* of the binary it was registered against, so
# even though the path (/Applications/kstars.app/.../dbus-daemon) is unchanged,
# the just-swapped binary is a different build and the cached job goes stale
# ("needs LWCR update") — next launch then hangs after "DBus Started" with no
# window. install.sh's pre-build check only catches a *missing* Program path;
# here the path stays valid, so recycle unconditionally after every swap.
UID_NUM=$(id -u)
launchctl bootout "gui/$UID_NUM/org.freedesktop.dbus-kstars" 2>/dev/null || true
rm -f "$HOME/Library/LaunchAgents/org.freedesktop.dbus-kstars.plist"
# Drop a dead session-bus socket reference if the old job left one behind.
sock=$(launchctl getenv DBUS_LAUNCHD_SESSION_BUS_SOCKET 2>/dev/null || true)
[[ -n "$sock" && ! -S "$sock" ]] && launchctl unsetenv DBUS_LAUNCHD_SESSION_BUS_SOCKET
# KStars re-registers a fresh, correct job pointing at /Applications/kstars.app
# on its next launch.

# Keep LaunchServices pointed at exactly one copy (/Applications/kstars.app),
# and keep Spotlight out of the Craft build tree entirely — see README's "Which
# copy do I actually run" section. The build-intermediate .app bundles (archive,
# archive-dbg, image-RelWithDebInfo-*, work/build/{bin,kstars}) plus Craft's own
# install prefix are regenerated by every `craft kstars` / `craft --package
# kstars` run, so this has to happen on every update, not just the initial
# install. Enumerate them rather than hardcode a list that drifts between
# Craft/KStars versions.
touch "$CRAFT_PREFIX/.metadata_never_index"
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
if [[ -x "$LSREGISTER" ]]; then
	while IFS= read -r stale; do
		[[ -n "$stale" ]] && "$LSREGISTER" -u "$stale" 2>/dev/null || true
	done < <(find "$CRAFT_PREFIX" -maxdepth 10 -type d -iname 'kstars.app' 2>/dev/null)
fi

log "Done"
mdls -name kMDItemVersion /Applications/kstars.app 2>/dev/null || true
echo "Updated: /Applications/kstars.app"
