#!/usr/bin/env bash
#
# update_kstars.sh — build a newer KStars, package it, and swap it into
# /Applications/kstars.app. Same workflow as install.sh's steps 4-6, split
# out for when you already have Craft bootstrapped and just want to update.
# See README.md ("Updating to a newer KStars") for the manual equivalent.
#
# Usage:
#   ./update_kstars.sh
#   CRAFT_PREFIX=/other/path ./update_kstars.sh
#
# Requires an existing Craft install at $CRAFT_PREFIX (default: ~/CraftRoot)
# — run install.sh first if you don't have one yet.

set -euo pipefail

CRAFT_PREFIX="${CRAFT_PREFIX:-$HOME/CraftRoot}"

log() { echo ""; echo "== $* =="; }

if [[ ! -f "$CRAFT_PREFIX/craft/craftenv.sh" ]]; then
	echo "error: no Craft install found at $CRAFT_PREFIX. Run install.sh first." >&2
	exit 1
fi

# shellcheck disable=SC1091
source "$CRAFT_PREFIX/craft/craftenv.sh"

# ---------------------------------------------------------------------------
# 1. Bauen: check for and pull in a newer KStars/INDI
# ---------------------------------------------------------------------------
log "Checking for a newer KStars"
craft --check-for-updates kstars || true

log "Building KStars (rebuilds INDI too if it changed)"
craft kstars

# ---------------------------------------------------------------------------
# 2. DMG: package a fresh self-contained .dmg
# ---------------------------------------------------------------------------
log "Packaging a self-contained .dmg"
craft --package kstars

DMG=$(find "$CRAFT_PREFIX/tmp" -maxdepth 1 -iname "kstars-*.dmg" -newer "$CRAFT_PREFIX/craft/craftenv.sh" 2>/dev/null | head -1)
if [[ -z "$DMG" ]]; then
	DMG=$(find "$CRAFT_PREFIX/tmp" -maxdepth 1 -iname "kstars-*.dmg" 2>/dev/null | sort | tail -1)
fi
if [[ -z "$DMG" ]]; then
	echo "error: craft --package succeeded but no .dmg found under $CRAFT_PREFIX/tmp" >&2
	exit 1
fi
echo "DMG: $DMG"

# ---------------------------------------------------------------------------
# 3. DMG updaten: swap it into /Applications/kstars.app
# ---------------------------------------------------------------------------
log "Installing the updated app to /Applications/kstars.app"
MOUNT_DIR=$(mktemp -d /tmp/kstars-dmg-mount.XXXXXX)
hdiutil attach "$DMG" -nobrowse -mountpoint "$MOUNT_DIR" >/dev/null
rm -rf /Applications/kstars.app
cp -R "$MOUNT_DIR/kstars.app" /Applications/kstars.app
xattr -cr /Applications/kstars.app
hdiutil detach "$MOUNT_DIR" >/dev/null

# Keep LaunchServices pointed at exactly one copy — see README's "Which copy
# do I actually run" section. Build-intermediate copies get regenerated by
# every `craft kstars`/`craft --package kstars` run, so this needs to happen
# on every update, not just the initial install.
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
if [[ -x "$LSREGISTER" ]]; then
	for stale in \
		"$CRAFT_PREFIX/Applications/KDE/kstars.app" \
		"$CRAFT_PREFIX/build/kde/applications/kstars/archive/Applications/KDE/kstars.app" \
		"$CRAFT_PREFIX/build/kde/applications/kstars/image-RelWithDebInfo-"*"/Applications/KDE/kstars.app" \
		"$CRAFT_PREFIX/build/kde/applications/kstars/work/build/kstars/KStars.app"; do
		[[ -e "$stale" ]] && "$LSREGISTER" -u "$stale" 2>/dev/null || true
	done
fi

log "Done"
mdls -name kMDItemVersion /Applications/kstars.app 2>/dev/null || true
echo "Updated: /Applications/kstars.app"
